# -*- coding: utf-8 -*-
"""
Campos da ficha DENGUE — Ficha de Investigação de Óbito por Arbovírus (Dengue)
Base: Protocolo de Investigação de Óbitos por Arbovírus Urbanos no Brasil —
Dengue, Chikungunya e Zika (MS/SVS, 2016):
  - Anexo A: Investigação de óbito por arbovírus — Prontuário (10 blocos)
  - Anexo B: Investigação de óbito por arbovírus — Entrevista domiciliar (5 blocos)

Formato: lista plana de strings (mesmo padrão de CAMPOS_PADRAO em app/utils/campos.py).
  - Checkbox: 'Código. Descrição: Opção'  → grupo = 'Código. Descrição'
  - Textarea: 'Código. Descrição'  (ou 'Código. Descrição - subcampo')
"""

CAMPOS_DENGUE = [
    # ================================================================
    # ANEXO A — PRONTUÁRIO
    # ================================================================

    # A1. Dados de Identificação
    'DI01. Nº SINAN',
    'DI02. Nº GAL',
    'DI03. Nome do paciente',
    'DI04. Data de nascimento',
    'DI05. Idade',
    'DI05. Unidade idade: Dias',
    'DI05. Unidade idade: Meses',
    'DI05. Unidade idade: Anos',
    'DI06. Sexo: Masculino',
    'DI06. Sexo: Feminino',
    'DI07. Nome da mãe',
    'DI08. Telefone',
    'DI09. Município de residência',
    'DI10. UF',
    'DI11. Endereço',
    'DI12. Bairro',
    'DI13. Ponto de referência',

    # A2. Dados de Internação
    'IT01. Nome do serviço de saúde',
    'IT02. Município de internação',
    'IT03. Data de admissão',
    'IT04. Unidade: PS',
    'IT04. Unidade: Clínica',
    'IT04. Unidade: UTI',
    'IT04. Unidade: Outro',
    'IT04.1. Outro (especificar)',
    'IT05. Estadiamento: A',
    'IT05. Estadiamento: B',
    'IT05. Estadiamento: C',
    'IT05. Estadiamento: D',
    'IT05. Estadiamento: Não realizado',
    'IT06. Hipótese diagnóstica inicial',

    # A3. Dados Clínicos
    'DC01. Sinais/sintomas antes da internação: Sim',
    'DC01. Sinais/sintomas antes da internação: Não',
    'DC02. Data de início dos sintomas',
    # DC03 — Sinais e sintomas (grupo de checkboxes + subcampos texto)
    'DC03. Sintomas: Febre',
    'DC03. Febre - data de início',
    'DC03. Febre - duração (dias)',
    'DC03. Febre - temperatura máxima (°C)',
    'DC03. Sintomas: Hipotermia',
    'DC03. Hipotermia - temperatura mínima (°C)',
    'DC03. Sintomas: Dor articular',
    'DC03. Dor articular extensão: Oligoarticular',
    'DC03. Dor articular extensão: Poliarticular',
    'DC03. Dor articular intensidade: Leve',
    'DC03. Dor articular intensidade: Moderada',
    'DC03. Dor articular intensidade: Intensa',
    'DC03. Sintomas: Exantema',
    'DC03. Exantema - data de início',
    'DC03. Exantema - duração (dias)',
    'DC03. Exantema: Pruriginoso',
    'DC03. Exantema: Macular',
    'DC03. Exantema: Maculo-papular',
    'DC03. Sintomas: Prurido',
    'DC03. Sintomas: Cefaleia',
    'DC03. Sintomas: Dor retroorbitária',
    'DC03. Sintomas: Mialgia',
    'DC03. Sintomas: Conjuntivite seca',
    'DC03. Sintomas: Artrite',
    'DC03. Sintomas: Tenossinovite',
    'DC03. Sintomas: Edema de membros',
    'DC03. Edema tipo: Articular',
    'DC03. Edema tipo: Periarticular',
    'DC03. Edema tipo: Disseminado',
    'DC03. Sintomas: Dor abdominal',
    'DC03. Dor abdominal intensidade: Leve',
    'DC03. Dor abdominal intensidade: Moderada',
    'DC03. Dor abdominal intensidade: Intensa',
    'DC03. Sintomas: Diarreia',
    'DC03. Sintomas: Náuseas',
    'DC03. Sintomas: Vômitos',
    'DC03. Sintomas: Calafrios',
    'DC03. Sintomas: Petéquias',
    'DC03. Sintomas: Equimose',
    'DC03. Sintomas: Epistaxe',
    'DC03. Sintomas: Hematoma',
    'DC03. Sintomas: Prostração',
    'DC03. Sintomas: Sonolência',
    'DC03. Sintomas: Irritabilidade',
    'DC03. Sintomas: Hipotensão postural',
    'DC03. Sintomas: Lipotimia',
    'DC03. Sintomas: Hepatomegalia',
    'DC03. Sintomas: Esplenomegalia',
    'DC03. Sintomas: Coriza',
    'DC03. Sintomas: Tosse',
    'DC03. Sintomas: Dispneia',
    'DC03. Sintomas: Dor de garganta',
    'DC03. Sintomas: Faringite',
    'DC03. Sintomas: Linfadenopatia',
    'DC03. Sintomas: Paresia',
    'DC03. Sintomas: Paralisia',
    'DC03. Sintomas: Outros',
    'DC03. Outros (especificar)',
    # DC04 — Comorbidades
    'DC04. Comorbidades: Sim',
    'DC04. Comorbidades: Não',
    'DC04. Comorbidade: Gestante',
    'DC04. Comorbidade: Puérpera',
    'DC04. Comorbidade: Hipertensão arterial sistêmica',
    'DC04. Comorbidade: Diabetes mellitus',
    'DC04. Comorbidade: Doença renal crônica',
    'DC04. Comorbidade: Doença acidopéptica',
    'DC04. Comorbidade: Obesidade',
    'DC04. Comorbidade: Cardiopatia crônica',
    'DC04. Comorbidade: Asma',
    'DC04. Comorbidade: Epilepsia',
    'DC04. Comorbidade: Doença hematológica',
    'DC04. Comorbidade: Tabagismo',
    'DC04. Comorbidade: Etilismo',
    'DC04. Comorbidade: Hepatite crônica',
    'DC04. Comorbidade: Cirrose hepática',
    'DC04. Comorbidade: Doenças reumatológicas',
    'DC04. Comorbidade: DPOC',
    'DC04. Comorbidade: Outras patologias',
    'DC04. Outras patologias (especificar)',
    # DC05 a DC14
    'DC05. Doença que afete resposta imunológica: Sim',
    'DC05. Doença que afete resposta imunológica: Não',
    'DC05. Doença que afete resposta imunológica: Não informado',
    'DC05.1. Especificar',
    'DC06. Descompensação de enfermidade crônica: Sim',
    'DC06. Descompensação de enfermidade crônica: Não',
    'DC06. Descompensação de enfermidade crônica: Não informado',
    'DC06.1. Especificar',
    'DC07. Outras manifestações após quadro agudo: Sim',
    'DC07. Outras manifestações após quadro agudo: Não',
    'DC07. Outras manifestações após quadro agudo: Não informado',
    'DC07.1. Especificar',
    'DC08. Manifestações neurológicas: Sim',
    'DC08. Manifestações neurológicas: Não',
    'DC08. Manifestação neurológica: Meningoencefalite',
    'DC08. Manifestação neurológica: Encefalite',
    'DC08. Manifestação neurológica: Convulsões',
    'DC08. Manifestação neurológica: Paresia',
    'DC08. Manifestação neurológica: Paralisia',
    'DC08. Manifestação neurológica: Neuropatia',
    'DC08. Manifestação neurológica: Síndrome de Guillain-Barré',
    'DC08. Manifestação neurológica: Síndrome cerebelar',
    'DC08. Manifestação neurológica: Encefalomielite aguda disseminada',
    'DC08. Manifestação neurológica: Agitação',
    'DC08. Manifestação neurológica: Alteração/rebaixamento de consciência',
    'DC08. Manifestação neurológica: Coma',
    'DC08. Manifestação neurológica: Sinais meníngeos',
    'DC08. Manifestação neurológica: Outras',
    'DC08. Outras (especificar)',
    'DC09. Manifestações oculares: Sim',
    'DC09. Manifestações oculares: Não',
    'DC09. Manifestação ocular: Neurite óptica',
    'DC09. Manifestação ocular: Iridiociclite',
    'DC09. Manifestação ocular: Episclerite',
    'DC09. Manifestação ocular: Retinite',
    'DC09. Manifestação ocular: Uveíte',
    'DC09. Manifestação ocular: Outras',
    'DC09. Outras (especificar)',
    'DC10. Manifestações dermatológicas: Sim',
    'DC10. Manifestações dermatológicas: Não',
    'DC10. Manifestação dermatológica: Hiperpigmentação fotossensível',
    'DC10. Manifestação dermatológica: Dermatose vesículo-bolhosa',
    'DC10. Manifestação dermatológica: Úlcera aftosa intertriginosa',
    'DC10. Manifestação dermatológica: Isquemia cutânea',
    'DC10. Manifestação dermatológica: Outras',
    'DC10. Outras (especificar)',
    'DC11. Quadro renal: Sim',
    'DC11. Quadro renal: Não',
    'DC11. Manifestação renal: Nefrite',
    'DC11. Manifestação renal: Insuficiência renal aguda',
    'DC11. Manifestação renal: Redução do débito urinário',
    'DC11. Manifestação renal: Alteração da cor da urina',
    'DC11. Manifestação renal: Outras',
    'DC11. Outras (especificar)',
    'DC12. Quadro hemorrágico: Sim',
    'DC12. Quadro hemorrágico: Não',
    'DC12. Manifestação hemorrágica: Hematêmese',
    'DC12. Manifestação hemorrágica: Melena',
    'DC12. Manifestação hemorrágica: Metrorragia volumosa',
    'DC12. Manifestação hemorrágica: Sangramento do SNC',
    'DC12. Manifestação hemorrágica: Sangramentos cutâneos',
    'DC12. Manifestação hemorrágica: Sangramento de mucosa oral',
    'DC12. Manifestação hemorrágica: Sangramento digestivo alto',
    'DC12. Manifestação hemorrágica: Sangramento digestivo baixo',
    'DC12. Manifestação hemorrágica: Sangramento cavitário (abdominal, torácico)',
    'DC12. Manifestação hemorrágica: Outros',
    'DC12. Outros (especificar)',
    'DC13. Evoluiu para choque: Sim',
    'DC13. Evoluiu para choque: Não',
    'DC13. Sinal de choque: Taquicardia',
    'DC13. Sinal de choque: Pulso débil ou inidentificável',
    'DC13. Sinal de choque: PA diferencial convergente (≤20 mmHg)',
    'DC13. Sinal de choque: Extremidades frias',
    'DC13. Sinal de choque: Tempo de enchimento capilar ≥3s',
    'DC13. Sinal de choque: Hipotensão arterial (PAS <90 mmHg)',
    'DC13. Sinal de choque: Outros',
    'DC13. Outros (especificar)',
    'DC14. Outras complicações: Sim',
    'DC14. Outras complicações: Não',
    'DC14. Complicação: Miocardite',
    'DC14. Complicação: Discrasias hemorrágicas',
    'DC14. Complicação: Pneumonia',
    'DC14. Complicação: Insuficiência respiratória',
    'DC14. Complicação: Taquidispneia',
    'DC14. Complicação: Hepatite aguda',
    'DC14. Complicação: Pancreatite aguda',
    'DC14. Complicação: Hipoadrenalismo',
    'DC14. Complicação: Icterícia',
    'DC14. Complicação: Edema agudo pulmonar',
    'DC14. Complicação: Infecção associada à assistência à saúde',
    'DC14. Complicação: Outras',
    'DC14. Outras (especificar)',

    # A4. Evolução Clínica
    'EC1. Remoção para UTI: Sim',
    'EC1. Remoção para UTI: Não',
    'EC1.1. Data de admissão na UTI',
    'EC1.2. Data de alta da UTI',
    'EC2. Evolução: Transferência',
    'EC2. Evolução: Alta',
    'EC2. Evolução: Óbito',
    'EC2. Data',
    'EC2. Para onde (transferência)',
    'EC3. DO linha a',
    'EC3. DO linha b',
    'EC3. DO linha c',
    'EC3. DO linha d',
    'EC3. DO linha I',
    'EC3. DO linha II',
    'EC4. Corpo encaminhado para necropsia: Sim',
    'EC4. Corpo encaminhado para necropsia: Não',
    'EC4. Laudo da necropsia',
    'EC5. Óbito fetal/<1 ano em relação ao parto: Antes',
    'EC5. Óbito fetal/<1 ano em relação ao parto: Durante',
    'EC5. Óbito fetal/<1 ano em relação ao parto: Após',
    'EC5. Óbito fetal/<1 ano em relação ao parto: Ignorado',

    # A5. Manejo Clínico
    'MC01. Soroterapia intravenosa: Sim',
    'MC01. Soroterapia intravenosa: Não',
    'MC02. Data de início da soroterapia',
    'MC03. Dias de uso',
    'MC04. Volume diário infundido',
    'MC05. Medicamentos durante a internação',

    # A6. Exames Laboratoriais Inespecíficos
    'LI01. Exame de sangue: Sim',
    'LI01. Exame de sangue: Não',
    'LI01. Resultados (hemograma/hematócrito/plaquetas)',
    'LI02. Punção liquórica: Sim',
    'LI02. Punção liquórica: Não',
    'LI02.1. Data da punção',
    'LI02.2. Aspecto: Límpido',
    'LI02.2. Aspecto: Turvo',
    'LI02.2. Aspecto: Hemorrágico',
    'LI02.2. Aspecto: Outro',
    'LI02.2. Outro (especificar)',
    'LI02.3. Análise bioquímica do líquor',
    'LI03. Exame de imagem: Sim',
    'LI03. Exame de imagem: Não',
    'LI03. Exames de imagem (especificar)',

    # A7. Exames Laboratoriais Específicos
    'LE01. Exame etiológico: Sim',
    'LE01. Exame etiológico: Não',
    'LE01. Sorologia IgM: Realizado',
    'LE01. Sorologia IgM: Não realizado',
    'LE01. Sorologia IgM: Reagente',
    'LE01. Sorologia IgM: Não reagente',
    'LE01. Sorologia IgM: Inconclusivo',
    'LE01. NS1: Realizado',
    'LE01. NS1: Não realizado',
    'LE01. NS1: Reagente',
    'LE01. NS1: Não reagente',
    'LE01. NS1: Inconclusivo',
    'LE01. RT-PCR: Realizado',
    'LE01. RT-PCR: Não realizado',
    'LE01. RT-PCR: Detectável',
    'LE01. RT-PCR: Não detectável',
    'LE01. RT-PCR: Inconclusivo',
    'LE01. Imuno-histoquímica: Realizado',
    'LE01. Imuno-histoquímica: Não realizado',
    'LE01. Imuno-histoquímica: Positivo',
    'LE01. Imuno-histoquímica: Negativo',
    'LE01. Imuno-histoquímica: Inconclusivo',
    'LE01. Outra técnica/resultado',
    'LE02. Isolamento por cultura: Sim',
    'LE02. Isolamento por cultura: Não',
    'LE02. Agente isolado (especificar)',
    'LE03. Alíquota guardada em laboratório: Sim',
    'LE03. Alíquota guardada em laboratório: Não',
    'LE03. Onde',

    # A8. Encerramento
    'EN01. Caso encerrado: Sim',
    'EN01. Caso encerrado: Não',
    'EN02. Critério: Laboratorial',
    'EN02. Critério: Clínico-epidemiológico',
    'EN03. Classificação: 10 — Dengue',
    'EN03. Classificação: 11 — Dengue com sinais de alarme',
    'EN03. Classificação: 12 — Dengue grave',
    'EN03. Classificação: Descartado',
    'EN03. Classificação: Óbito por outras causas',
    'EN03. Classificação: Em investigação',
    'EN04. Data do encerramento',

    # A9. Observações (Anexo A)
    'OBSA. Observações',

    # A10. Investigação (Anexo A)
    'IVA01. Data da investigação',
    'IVA02. Investigador',
    'IVA03. Função/Unidade',

    # ================================================================
    # ANEXO B — ENTREVISTA DOMICILIAR
    # ================================================================

    # B1. Dados de Identificação do Entrevistado
    'EDI01. ID',
    'EDI02. Nome do entrevistado',
    'EDI03. Data de nascimento',
    'EDI04. Idade',
    'EDI04. Unidade idade: Dias',
    'EDI04. Unidade idade: Meses',
    'EDI04. Unidade idade: Anos',
    'EDI05. Sexo: Masculino',
    'EDI05. Sexo: Feminino',
    'EDI06. Grau de parentesco com o caso',
    'EDI07. Município de residência',
    'EDI08. UF',
    'EDI09. Endereço',
    'EDI10. Ponto de referência',
    'EDI11. Telefone',

    # B2. Assistência à Saúde
    'AS01. Ficou doente antes do óbito: Sim',
    'AS01. Ficou doente antes do óbito: Não',
    'AS01. Ficou doente antes do óbito: Não sei',
    'AS01.1. Data de início dos sintomas',
    'AS02. Sintoma: Febre',
    'AS02. Febre - data de início',
    'AS02. Febre - duração (dias)',
    'AS02. Febre - temperatura máxima (°C)',
    'AS02. Sintoma: Hipotermia',
    'AS02. Sintoma: Dor articular',
    'AS02. Sintoma: Exantema',
    'AS02. Sintoma: Prurido',
    'AS02. Sintoma: Cefaleia',
    'AS02. Sintoma: Dor retroorbitária',
    'AS02. Sintoma: Mialgia',
    'AS02. Sintoma: Conjuntivite seca',
    'AS02. Sintoma: Dor abdominal',
    'AS02. Sintoma: Diarreia',
    'AS02. Sintoma: Náuseas',
    'AS02. Sintoma: Vômitos',
    'AS02. Sintoma: Calafrios',
    'AS02. Sintoma: Petéquias',
    'AS02. Sintoma: Dispneia',
    'AS02. Sintoma: Dor de garganta',
    'AS02. Sintoma: Faringite',
    'AS02. Sintoma: Linfadenopatia',
    'AS02. Sintoma: Paresia',
    'AS02. Sintoma: Paralisia',
    'AS02. Sintoma: Outros',
    'AS02. Outros (especificar)',
    'AS03. Medicação sem prescrição: Sim',
    'AS03. Medicação sem prescrição: Não',
    'AS03. Medicamentos (classe, medicamento/dose, início, término)',
    'AS04. Procurou atendimento médico: Sim',
    'AS04. Procurou atendimento médico: Não',
    'AS05. Quantos serviços de saúde procurou',
    'AS31. Descrição dos atendimentos',

    # B3. Contactantes
    'C01. Alguém que morava com o caso adoeceu: Sim',
    'C01. Alguém que morava com o caso adoeceu: Não',
    'C02. Quantas pessoas adoeceram',
    'C03. Sintoma de contactante: Febre',
    'C03. Sintoma de contactante: Cefaleia',
    'C03. Sintoma de contactante: Mialgia',
    'C03. Sintoma de contactante: Artralgia',
    'C03. Sintoma de contactante: Artrite',
    'C03. Sintoma de contactante: Edema de membros',
    'C03. Sintoma de contactante: Tenossinovite',
    'C03. Sintoma de contactante: Exantema',
    'C03. Sintoma de contactante: Sangramento de mucosa',
    'C03. Sintoma de contactante: Prostração',
    'C03. Sintoma de contactante: Coriza',
    'C03. Sintoma de contactante: Diarreia',
    'C03. Sintoma de contactante: Tosse',
    'C03. Sintoma de contactante: Vômitos',
    'C03. Sintoma de contactante: Insuficiência respiratória',
    'C03. Sintoma de contactante: Dor abdominal',
    'C03. Sintoma de contactante: Conjuntivite',
    'C03. Sintoma de contactante: Sonolência',
    'C03. Sintoma de contactante: Linfadenopatia',
    'C03. Sintoma de contactante: Irritabilidade',
    'C03. Sintoma de contactante: Hipotensão postural ou lipotimia',
    'C03. Outros (especificar)',

    # B4. Observações (Anexo B)
    'OBSB. Observações',

    # B5. Investigação (Anexo B)
    'IVB01. Data da investigação',
    'IVB02. Investigador',
]


def obter_campos_dengue():
    """Retorna a lista de campos da ficha DENGUE no formato de CAMPOS_PADRAO."""
    return list(CAMPOS_DENGUE)
