"""baseline v1.1

Revision ID: 4f239821b7c0
Revises: 
Create Date: 2026-10-08 08:01:47.384763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f239821b7c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('capitulo', sa.String(length=100), nullable=True),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cids_codigo'), ['codigo'], unique=True)

    op.create_table('estabelecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnes', sa.String(length=7), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estabelecimentos_cnes'), ['cnes'], unique=True)
        batch_op.create_index(batch_op.f('ix_estabelecimentos_nome'), ['nome'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_usuario'), ['usuario'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=100), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados_antes', sa.Text(), nullable=True),
    sa.Column('dados_depois', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entidade_data', ['entidade', 'criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entidade_id'), ['entidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index('ix_audit_usuario_data', ['usuario_id', 'criado_em'], unique=False)

    op.create_table('obitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_obito', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('nome_mae', sa.String(length=200), nullable=True),
    sa.Column('nome_pai', sa.String(length=200), nullable=True),
    sa.Column('numero_dob', sa.String(length=50), nullable=True),
    sa.Column('causa_morte', sa.Text(), nullable=True),
    sa.Column('causa_morte_cid', sa.String(length=10), nullable=True),
    sa.Column('causas_morte_cids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('local_obito', sa.String(length=50), nullable=True),
    sa.Column('municipio_ocorrencia', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obitos_causa_morte_cid'), ['causa_morte_cid'], unique=False)
        batch_op.create_index(batch_op.f('ix_obitos_data_nascimento'), ['data_nascimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_obitos_data_obito'), ['data_obito'], unique=False)
        batch_op.create_index(batch_op.f('ix_obitos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_obitos_numero_dob'), ['numero_dob'], unique=False)

    op.create_table('investigacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obito_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('conclusao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obito_id'], ['obitos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigacoes_obito_id'), ['obito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigacoes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigacoes_tipo'), ['tipo'], unique=False)

    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigacao_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=200), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigacao_id'], ['investigacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexos_investigacao_id'), ['investigacao_id'], unique=False)

    op.create_table('investigacao_campos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigacao_id', sa.Integer(), nullable=False),
    sa.Column('nome_campo', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigacao_id'], ['investigacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigacao_campos', schema=None) as batch_op:
        batch_op.create_index('ix_investigacao_campo_nome', ['investigacao_id', 'nome_campo'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigacao_campos_investigacao_id'), ['investigacao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigacao_campos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigacao_campos_investigacao_id'))
        batch_op.drop_index('ix_investigacao_campo_nome')

    op.drop_table('investigacao_campos')
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexos_investigacao_id'))

    op.drop_table('anexos')
    with op.batch_alter_table('investigacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigacoes_tipo'))
        batch_op.drop_index(batch_op.f('ix_investigacoes_status'))
        batch_op.drop_index(batch_op.f('ix_investigacoes_obito_id'))

    op.drop_table('investigacoes')
    with op.batch_alter_table('obitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obitos_numero_dob'))
        batch_op.drop_index(batch_op.f('ix_obitos_nome'))
        batch_op.drop_index(batch_op.f('ix_obitos_data_obito'))
        batch_op.drop_index(batch_op.f('ix_obitos_data_nascimento'))
        batch_op.drop_index(batch_op.f('ix_obitos_causa_morte_cid'))

    op.drop_table('obitos')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_usuario_data')
        batch_op.drop_index(batch_op.f('ix_audit_logs_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entidade_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entidade'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_criado_em'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_acao'))
        batch_op.drop_index('ix_audit_entidade_data')

    op.drop_table('audit_logs')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_usuario'))

    op.drop_table('usuarios')
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estabelecimentos_nome'))
        batch_op.drop_index(batch_op.f('ix_estabelecimentos_cnes'))

    op.drop_table('estabelecimentos')
    with op.batch_alter_table('cids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cids_codigo'))

    op.drop_table('cids')
    # ### end Alembic commands ###
